version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: negocios-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./backend/.env.production
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - negocios-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web Admin
  web-admin:
    build:
      context: ./web-admin
      dockerfile: Dockerfile
    container_name: negocios-web-admin
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - ./web-admin/.env.production
    volumes:
      - admin_uploads:/app/uploads
    networks:
      - negocios-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend

  # Nginx Reverse Proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: negocios-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - negocios-network
    restart: unless-stopped
    depends_on:
      - backend
      - web-admin

volumes:
  backend_uploads:
    driver: local
  admin_uploads:
    driver: local

networks:
  negocios-network:
    driver: bridge