export const NOVA_TERRA_CENTER_LAT = -2.5712107;
export const NOVA_TERRA_CENTER_LNG = -44.1521924;
export const NOVA_TERRA_DEFAULT_ZOOM = 14;
export const USER_LOCATION_ZOOM = 16;

export const NOVA_TERRA_CENTER: [number, number] = [NOVA_TERRA_CENTER_LAT, NOVA_TERRA_CENTER_LNG];
